# Python RPG
# Alex Galhardo Vieira
# https://github.com/AlexGalhardo/Python-RPG
# aleexgvieira@gmail.com
# https://alexgalhardo.com

# !/usr/bin/python3
# coding: utf-8 

# ./Python/Global/GLOBAL_PITS_OF_INFERNO_VARIABLES.py

# Normal Monsters Status
GLOBAL_BEAR_NAME = "Bear"
GLOBAL_BEAR_LIFE = 100
GLOBAL_BEAR_WEAPON_ATTACK = 10
GLOBAL_BEAR_EXPERIENCE = 350

GLOBAL_HUNTER_NAME = "Hunter"
GLOBAL_HUNTER_LIFE = 250
GLOBAL_HUNTER_WEAPON_ATTACK = 15
GLOBAL_HUNTER_EXPERIENCE = 550

GLOBAL_CYCLOPS_NAME = "Cyclops"
GLOBAL_CYCLOPS_LIFE = 500
GLOBAL_CYCLOPS_WEAPON_ATTACK = 20
GLOBAL_CYCLOPS_EXPERIENCE = 1200


# Magic Monsters Status
GLOBAL_DRAGON_NAME = "Dragon"
GLOBAL_DRAGON_LIFE = 1000
GLOBAL_DRAGON_MAGIC_ATTACK = 30
GLOBAL_DRAGON_EXPERIENCE = 2000

GLOBAL_INFERNALIST_NAME = "Infenalist"
GLOBAL_INFERNALIST_LIFE = 1000
GLOBAL_INFERNALIST_MAGIC_ATTACK = 25
GLOBAL_INFERNALIST_EXPERIENCE = 3000

GLOBAL_WARLOCK_NAME = "WARLOCK"
GLOBAL_WARLOCK_LIFE = 1500
GLOBAL_WARLOCK_MAGIC_ATTACK = 40
GLOBAL_WARLOCK_EXPERIENCE = 4000


# Demon Monsters Status
GLOBAL_FURY_NAME = "Fury"
GLOBAL_FURY_LIFE = 2000
GLOBAL_FURY_WEAPON_ATTACK = 30
GLOBAL_FURY_MAGIC_ATTACK = 45
GLOBAL_FURY_EXPERIENCE = 6000

GLOBAL_DARKTORTURER_NAME = "Dark Torturer"
GLOBAL_DARKTORTURER_LIFE = 2500
GLOBAL_DARKTORTURER_WEAPON_ATTACK = 35
GLOBAL_DARKTORTURER_MAGIC_ATTACK = 45
GLOBAL_DARKTORTURER_EXPERIENCE = 8500

GLOBAL_DEMON_NAME = "Demon"
GLOBAL_DEMON_LIFE = 3500
GLOBAL_DEMON_WEAPON_ATTACK = 40
GLOBAL_DEMON_MAGIC_ATTACK = 55
GLOBAL_DEMON_EXPERIENCE = 12000


# BOSS Monsters Status
GLOBAL_MORGAROTH_NAME = "Morgaroth"
GLOBAL_MORGAROTH_LIFE = 10000
GLOBAL_MORGAROTH_WEAPON_ATTACK = 60
GLOBAL_MORGAROTH_MAGIC_ATTACK = 60
GLOBAL_MORGAROTH_EXPERIENCE = 25000

