# Python RPG
# Alex Galhardo Vieira
# https://github.com/AlexGalhardo/Python-RPG
# aleexgvieira@gmail.com
# https://alexgalhardo.com

# !/usr/bin/python3
# coding: utf-8 

# ./Python/Global/GLOBAL_CHARACTERS_VARIABLES.py

# Knight Status
KNIGHT_INITIAL_LIFE = 750
KNIGHT_INITIAL_MANA = 200

KNIGHT_ADD_LIFE_FOR_LEVEL = 100
KNIGHT_ADD_MANA_FOR_LEVEL = 50

KNIGHT_LIGHT_SPELL_MANA_USED = 50
KNIGHT_MEDIUM_SPELL_MANA_USED = 100
KNIGHT_STRONG_SPELL_MANA_USED = 200

KNIGHT_REG_LIFE_EACH_TURN = 25
KNIGHT_REG_MANA_EACH_TURN = 10


# Paladin Status
PALADIN_INITIAL_LIFE = 650
PALADIN_INITIAL_MANA = 350

PALADIN_ADD_LIFE_FOR_LEVEL = 75
PALADIN_ADD_MANA_FOR_LEVEL = 75

PALADIN_LIGHT_SPELL_MANA_USED = 50
PALADIN_MEDIUM_SPELL_MANA_USED = 100
PALADIN_STRONG_SPELL_MANA_USED = 200

PALADIN_REG_LIFE_EACH_TURN = 15
PALADIN_REG_MANA_EACH_TURN = 15


# Mage Status
MAGE_INITIAL_LIFE = 500
MAGE_INITIAL_MANA = 500

MAGE_ADD_LIFE_FOR_LEVEL = 100
MAGE_ADD_MANA_FOR_LEVEL = 200

MAGE_LIGHT_SPELL_MANA_USED = 50
MAGE_MEDIUM_SPELL_MANA_USED = 100
MAGE_STRONG_SPELL_MANA_USED = 200

MAGE_REG_LIFE_EACH_TURN = 10
MAGE_REG_MANA_EACH_TURN = 25

MAGE_MEDIUM_HEALING_MANA_USED = 100
MAGE_STRONG_HEALING_MANA_USED = 200

